apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-nginx   # changes to: {{ .Release.name }}-nginx
  labels:
    app: nginx
spec:
  replicas: 2 #it changesto : {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-chart # it changes to : {{ .Chart.Name }}
          image: nginx:1.16.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80