apiVersion: v1
kind: service 
metadata:
  name: lb-service
labels:
  app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx-deployment
  ports:
  - name:  http 
    port: 80
    protocol: TCP
    targetPort: 80