apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  resources:
    requests:
      storage: 1Gi
  StorageClassName: managed-premium-retain
  accessModes:
    - ReadWriteOnce # readwriteonce, readwritemany, readwirteonly , readwirtyeoncepod
