apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicas
  labels:
    app: webapp
    type: front-end
spec:
  # modify replicas according to your case
  replicas: 5
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - name: web
          containerPort:  80
          protocol: TCP
