apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  type: Opaque
data:
  db_name: "primarkdb"
  db_password: "Password@123"
---

apiVersion: v1
kind: Pod
metadata:
  name:  configmap-pod
spec:
  containers:
    - name: busybox
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 500Mi
      image: busybox
      command: ["bin/bash","-c","env"]
      env:
        - name: DATABASE_HOST
          value: "myrds.amazon.com/primark"
        - name: DATABASENAME
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: db_name
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: db_password
