apiVersion: v1
kind:
metadata:
  name:  nginx
spec:
  containers:
    - name:  container
      image:  alpine
      volumeMounts:
        - name:  volume
        mountPath:  "/mnt/azure"
  volumes:
    - name:  volume
      persistentVolumeClaim:
        claimName: azure-managed-disk 
